// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SU.Backend.Database;

#nullable disable

namespace SU.Backend.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240922120419_Added_FK_1")]
    partial class Added_FK_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SU.Backend.Models.Customers.CompanyCustomer", b =>
                {
                    b.Property<int>("CompanyCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyCustomerId"), 1L, 1);

                    b.Property<string>("CompanyAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLandlineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonPhonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyCustomerId");

                    b.ToTable("CompanyCustomer");
                });

            modelBuilder.Entity("SU.Backend.Models.Customers.PrivateCustomer", b =>
                {
                    b.Property<int>("PrivateCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrivateCustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrivateCustomerId");

                    b.ToTable("PrivateCustomers");
                });

            modelBuilder.Entity("SU.Backend.Models.Employee.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("AgentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseSalary")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerEmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SU.Backend.Models.Employee.EmployeeRoleAssignment", b =>
                {
                    b.Property<int>("EmployeeRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeRoleAssignmentId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeRoleAssignmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeRoleAssignments");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", b =>
                {
                    b.Property<int>("InsuranceCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceCoverageId"), 1L, 1);

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("InsuranceCoverageId");

                    b.HasIndex("InsuranceId")
                        .IsUnique();

                    b.ToTable("InsuranceCoverages");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.LiabilityCoverage", b =>
                {
                    b.Property<int>("LiabilityCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiabilityCoverageId"), 1L, 1);

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InsuranceCoverageId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LiabilityCoverageId");

                    b.HasIndex("InsuranceCoverageId")
                        .IsUnique();

                    b.ToTable("LiabilityCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PrivateCoverage", b =>
                {
                    b.Property<int>("PrivateCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrivateCoverageId"), 1L, 1);

                    b.Property<int>("InsuranceCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("InsuredPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PrivateCoverageOptionId")
                        .HasColumnType("int");

                    b.HasKey("PrivateCoverageId");

                    b.HasIndex("InsuranceCoverageId")
                        .IsUnique();

                    b.HasIndex("InsuredPersonId");

                    b.HasIndex("PrivateCoverageOptionId");

                    b.ToTable("PrivateCoverages");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PrivateCoverageOption", b =>
                {
                    b.Property<int>("PrivateCoverageOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrivateCoverageOptionId"), 1L, 1);

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PrivateCoverageOptionId");

                    b.ToTable("PrivateCoverageOption");

                    b.HasData(
                        new
                        {
                            PrivateCoverageOptionId = 1,
                            CoverageAmount = 700000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 350m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 2,
                            CoverageAmount = 900000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 450m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 3,
                            CoverageAmount = 1100000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 550m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 4,
                            CoverageAmount = 1300000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 650m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 5,
                            CoverageAmount = 750000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 375m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 6,
                            CoverageAmount = 950000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 475m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 7,
                            CoverageAmount = 1150000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 575m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 8,
                            CoverageAmount = 1350000m,
                            InsuranceType = "ChildAccidentAndHealthInsurance",
                            MonthlyPremium = 675m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 9,
                            CoverageAmount = 300000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 150m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 10,
                            CoverageAmount = 400000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 200m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 11,
                            CoverageAmount = 500000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 250m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 12,
                            CoverageAmount = 350000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 175m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 13,
                            CoverageAmount = 450000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 225m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 14,
                            CoverageAmount = 550000m,
                            InsuranceType = "AdultAccidentAndHealthInsurance",
                            MonthlyPremium = 275m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 15,
                            CoverageAmount = 300000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 150m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 16,
                            CoverageAmount = 400000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 200m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 17,
                            CoverageAmount = 500000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 250m,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 18,
                            CoverageAmount = 350000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 175m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 19,
                            CoverageAmount = 450000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 225m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrivateCoverageOptionId = 20,
                            CoverageAmount = 550000m,
                            InsuranceType = "AdultLifeInsurance",
                            MonthlyPremium = 275m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PropertyAndInventoryCoverage", b =>
                {
                    b.Property<int>("PropertyAndInventoryCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyAndInventoryCoverageId"), 1L, 1);

                    b.Property<int>("InsuranceCoverageId")
                        .HasColumnType("int");

                    b.Property<decimal>("InventoryPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InventoryValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PropertyPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropertyAndInventoryCoverageId");

                    b.HasIndex("InsuranceCoverageId")
                        .IsUnique();

                    b.ToTable("PropertyAndInventoryCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.RizkZone", b =>
                {
                    b.Property<int>("RiskZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskZoneId"), 1L, 1);

                    b.Property<string>("RiskZoneLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ZoneFactor")
                        .HasColumnType("float");

                    b.HasKey("RiskZoneId");

                    b.ToTable("RizkZone");

                    b.HasData(
                        new
                        {
                            RiskZoneId = 1,
                            RiskZoneLevel = "Zone1",
                            ZoneFactor = 1.3
                        },
                        new
                        {
                            RiskZoneId = 2,
                            RiskZoneLevel = "Zone2",
                            ZoneFactor = 1.2
                        },
                        new
                        {
                            RiskZoneId = 3,
                            RiskZoneLevel = "Zone3",
                            ZoneFactor = 1.1000000000000001
                        },
                        new
                        {
                            RiskZoneId = 4,
                            RiskZoneLevel = "Zone4",
                            ZoneFactor = 1.0
                        });
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.VehicleInsuranceCoverage", b =>
                {
                    b.Property<int>("VehicleInsuranceCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInsuranceCoverageId"), 1L, 1);

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deductible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InsuranceCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("RiskZoneId")
                        .HasColumnType("int");

                    b.HasKey("VehicleInsuranceCoverageId");

                    b.HasIndex("InsuranceCoverageId")
                        .IsUnique();

                    b.HasIndex("RiskZoneId")
                        .IsUnique();

                    b.ToTable("VehicleInsuranceCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceId"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsuranceCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("InsurancePolicyHolderId")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InsuranceId");

                    b.HasIndex("InsurancePolicyHolderId")
                        .IsUnique();

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsuranceAddon", b =>
                {
                    b.Property<int>("InsuranceAddonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceAddonId"), 1L, 1);

                    b.Property<int>("InsuranceAddonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("InsuranceAddonId");

                    b.HasIndex("InsuranceAddonTypeId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsuranceAddons");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsuranceAddonType", b =>
                {
                    b.Property<int>("InsuranceAddonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceAddonTypeId"), 1L, 1);

                    b.Property<decimal>("BaseExtraPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceAddonTypeId");

                    b.ToTable("InsuranceAddonTypes");

                    b.HasData(
                        new
                        {
                            InsuranceAddonTypeId = 1,
                            BaseExtraPremium = 3.0000m,
                            CoverageAmount = 100000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 2,
                            BaseExtraPremium = 6.0000m,
                            CoverageAmount = 200000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 3,
                            BaseExtraPremium = 9.0000m,
                            CoverageAmount = 300000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 4,
                            BaseExtraPremium = 12.0000m,
                            CoverageAmount = 400000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 5,
                            BaseExtraPremium = 15.0000m,
                            CoverageAmount = 500000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 6,
                            BaseExtraPremium = 18.0000m,
                            CoverageAmount = 600000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 7,
                            BaseExtraPremium = 21.0000m,
                            CoverageAmount = 700000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 8,
                            BaseExtraPremium = 24.0000m,
                            CoverageAmount = 800000m,
                            Description = "SicknessAccident"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 9,
                            BaseExtraPremium = 0.2500m,
                            CoverageAmount = 500m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 10,
                            BaseExtraPremium = 0.5000m,
                            CoverageAmount = 1000m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 11,
                            BaseExtraPremium = 0.7500m,
                            CoverageAmount = 1500m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 12,
                            BaseExtraPremium = 1.0000m,
                            CoverageAmount = 2000m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 13,
                            BaseExtraPremium = 1.2500m,
                            CoverageAmount = 2500m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 14,
                            BaseExtraPremium = 1.5000m,
                            CoverageAmount = 3000m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 15,
                            BaseExtraPremium = 1.7500m,
                            CoverageAmount = 3500m,
                            Description = "LongTermSickness"
                        },
                        new
                        {
                            InsuranceAddonTypeId = 16,
                            BaseExtraPremium = 2.0000m,
                            CoverageAmount = 4000m,
                            Description = "LongTermSickness"
                        });
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsurancePolicyHolder", b =>
                {
                    b.Property<int>("InsurancePolicyHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsurancePolicyHolderId"), 1L, 1);

                    b.Property<int?>("CompanyCustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("PrivateCustomerId")
                        .HasColumnType("int");

                    b.HasKey("InsurancePolicyHolderId");

                    b.HasIndex("CompanyCustomerId");

                    b.HasIndex("PrivateCustomerId");

                    b.ToTable("InsurancePolicyHolders");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsuredPerson", b =>
                {
                    b.Property<int>("InsuredPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuredPersonId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuredPersonId");

                    b.ToTable("InsuredPersons");
                });

            modelBuilder.Entity("SU.Backend.Models.Employee.Employee", b =>
                {
                    b.HasOne("SU.Backend.Models.Employee.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SU.Backend.Models.Employee.EmployeeRoleAssignment", b =>
                {
                    b.HasOne("SU.Backend.Models.Employee.Employee", "Employee")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.Insurance", "Insurance")
                        .WithOne("InsuranceCoverage")
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", "InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.LiabilityCoverage", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", "InsuranceCoverage")
                        .WithOne("LiabilityCoverage")
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.LiabilityCoverage", "InsuranceCoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PrivateCoverage", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", "InsuranceCoverage")
                        .WithOne("PrivateCoverage")
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.PrivateCoverage", "InsuranceCoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SU.Backend.Models.Insurance.InsuredPerson", "InsuredPerson")
                        .WithMany("PrivateCoverages")
                        .HasForeignKey("InsuredPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SU.Backend.Models.Insurance.Coverage.PrivateCoverageOption", "PrivateCoverageOption")
                        .WithMany("PrivateCoverages")
                        .HasForeignKey("PrivateCoverageOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceCoverage");

                    b.Navigation("InsuredPerson");

                    b.Navigation("PrivateCoverageOption");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PropertyAndInventoryCoverage", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", "InsuranceCoverage")
                        .WithOne("PropertyAndInventoryCoverage")
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.PropertyAndInventoryCoverage", "InsuranceCoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.VehicleInsuranceCoverage", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", "InsuranceCoverage")
                        .WithOne("VehicleInsuranceCoverage")
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.VehicleInsuranceCoverage", "InsuranceCoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SU.Backend.Models.Insurance.Coverage.RizkZone", "RiskZone")
                        .WithOne()
                        .HasForeignKey("SU.Backend.Models.Insurance.Coverage.VehicleInsuranceCoverage", "RiskZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsuranceCoverage");

                    b.Navigation("RiskZone");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Insurance", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.InsurancePolicyHolder", "InsurancePolicyHolder")
                        .WithOne("Insurance")
                        .HasForeignKey("SU.Backend.Models.Insurance.Insurance", "InsurancePolicyHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicyHolder");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsuranceAddon", b =>
                {
                    b.HasOne("SU.Backend.Models.Insurance.InsuranceAddonType", "InsuranceAddonType")
                        .WithMany()
                        .HasForeignKey("InsuranceAddonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SU.Backend.Models.Insurance.Insurance", "Insurance")
                        .WithMany("InsuranceAddons")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("InsuranceAddonType");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsurancePolicyHolder", b =>
                {
                    b.HasOne("SU.Backend.Models.Customers.CompanyCustomer", "CompanyCustomer")
                        .WithMany()
                        .HasForeignKey("CompanyCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SU.Backend.Models.Customers.PrivateCustomer", "PrivateCustomer")
                        .WithMany()
                        .HasForeignKey("PrivateCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyCustomer");

                    b.Navigation("PrivateCustomer");
                });

            modelBuilder.Entity("SU.Backend.Models.Employee.Employee", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.InsuranceCoverage", b =>
                {
                    b.Navigation("LiabilityCoverage");

                    b.Navigation("PrivateCoverage");

                    b.Navigation("PropertyAndInventoryCoverage");

                    b.Navigation("VehicleInsuranceCoverage");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Coverage.PrivateCoverageOption", b =>
                {
                    b.Navigation("PrivateCoverages");
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.Insurance", b =>
                {
                    b.Navigation("InsuranceAddons");

                    b.Navigation("InsuranceCoverage")
                        .IsRequired();
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsurancePolicyHolder", b =>
                {
                    b.Navigation("Insurance")
                        .IsRequired();
                });

            modelBuilder.Entity("SU.Backend.Models.Insurance.InsuredPerson", b =>
                {
                    b.Navigation("PrivateCoverages");
                });
#pragma warning restore 612, 618
        }
    }
}
